name: Vixio
description: Vixio, The Discord addon created to meet all of your Discord needs.
main: me.iblitzkriegi.vixio.Vixio
version: 2.0.0-dev3
author: Blitz
website: http://vixio.space
depend: [Skript]
